### ISSUE TITLE
Missing instructions around vim

### ISSUE THREAD

**Issue by JohnTarr** [ianmiell/learn-git-the-hard-way#4]
This book is really helping me get my head around git, but there is a confusing piece on the first commit. You don't give instruction to use the -m flag, so it brings up vim, asking for the commit message. I had to google to understand that this was the vim editor and then how to make my changes and save and exit.

Not sure if you intended for the user to have to figure this out, but it was fairly confusing when trying to learn git.

Really appreciate the book, just hoping to save someone else the confusion.

**Comment by JohnTarr** [comment]
Ignore, just caught readme, with note that users should have knowledge of Linux command line.

**Comment by ianmiell** [comment]
Have added a note, as this would be confusing to many readers.
